batch_size: 11 #22
n_workers: 16
#iterations: 20000000
iterations: 10000
eval_every: 1
accumulate_grad_batches: 1
fp16: False
clip_denoised: True
ema_rate: 0.999

lr: 1e-4
wd: "0"

#fine_tune_from: lightning_logs/CASA_power2/best_epoch=237_step=99960.ckpt
fine_tune_from: null
schedule_sampler: uniform

model:
  use_y_conditioning: False
  diffusion_steps: 1000

dataset:
  image_path: D:\datasets\radio_images\D1 #D1 - 1-5 radio sources
  label_path:
  size: 128
  n_classes:
  n_channels: 1
  from_uv: False
  real_data: False
  power: 2
  use_zeros: True


comment: formal_run_with_early_stopping_scheduler
