batch_size: 11 #22
n_workers: 16
iterations: 20000000
#iterations: 10000
eval_every: 1
accumulate_grad_batches: 1
fp16: False
clip_denoised: True
ema_rate: 0.999

lr: 1e-4
wd: "0"

#fine_tune_from: lightning_logs/CASA_power2/best_epoch=237_step=99960.ckpt
fine_tune_from: null
schedule_sampler: uniform

model:
  use_y_conditioning: False
  diffusion_steps: 1000

latent:
  enabled: True
  dim: 32
  project_channels: 16
  beta_max: 0.1
  beta_warmup_steps: 1000
  free_bits: 0.0
  prior_freeze_steps: 0
  prior:
    base_channels: 32
    num_layers: 3
    max_channels: 256
  encoder:
    base_channels: 32
    num_layers: 3
    max_channels: 256

dataset:
#  image_path: /home/ldingaj/dataset/radio_images
  image_path: D:\datasets\radio_images
  label_path:
  size: 512
  n_classes:
  n_channels: 1
  from_uv: False
  real_data: False
  power: 2
  use_zeros: True


comment: test_run_VI
